version: '3.9'

services:

  db:
    image: postgres
    container_name: ecommerce-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: ecommerce
    restart: always
    networks:
      - workspace
    expose:
      - 5432

  ecommerce-api:
    build:
      dockerfile: Dockerfile
    container_name: ecommerce-api
    restart: on-failure
    ports:
      - "9091:9090"
    environment:
        - SPRING_PROFILES_ACTIVE=dockerDev
    expose:
      - 9090
    networks:
      - workspace
    depends_on:
      - db

networks:
  workspace:
    driver: bridge