version: '3.3'

services:

  db:
    image: postgres
    container_name: ecommerce-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${BD_USERNAME}
      POSTGRES_USER: ${BD_PASSWORD}
      POSTGRES_DATABASE: ecommerce
    restart: always
    networks:
      - workspace
    expose:
      - 5432

  ecommecer-api:
    build:
      dockerfile: Dockerfile
    container_name: ecommerce-api
    restart: on-failure
    ports:
      - "9091:9090"
    environment:
      SPRING_PROFILES_ACTIVE: dockerDev
    expose:
      - 9090
    networks:
      - workspace
    depends_on:
      - db

networks:
  workspace:
    driver: bridge