
name: Continuos Integration Github Actions

on:
  push:
    branches: 
     - main
     - develop
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: ./projetovendas
      run: mvn clean package 

    - name: Docker Compose Build
      working-directory: ./projetovendas
      run: docker compose build

    - name: Push To Docker Hub
      run: |
        docker tag projetovendas-ecommecer-api ${{secrets.DOCKER_USERNAME}}/projetovendas-ecommecer-api:${{ github.run_id }}
        docker push ${{secrets.DOCKER_USERNAME}}/projetovendas-ecommecer-api:${{ github.run_id }}
        docker push ${{secrets.DOCKER_USERNAME}}/projetovendas-ecommecer-api:latest



      
